### ISSUE TITLE
运行出错，mac下卡住，win下死循环

### ISSUE THREAD

**Issue by 1amfine2333** [Ormicron/chatViewTool#1]
如题，mac下卡住
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/24676292/177730328-5a7afae0-5d1f-410f-8a0a-f12df1439543.png">
win下死循环
<img width="715" alt="image" src="https://user-images.githubusercontent.com/24676292/177730733-0cba1d36-0318-4503-a32e-82762a224473.png">

**Comment by Ormicron** [comment]
确认下运行目录，以及数据库所在目录读写权限。

**Comment by Ormicron** [comment]
MAC下的应该是解密成功了，可以直接查看数据库。解密完成后数据页和最终数据页不匹配是由于实际的聊天记录大小没有将申请的页数完全写完导致的，不影响正常解密。
