### ISSUE TITLE
错误: 缺少 JavaFX 运行时组件, 需要使用该组件来运行此应用程序

### ISSUE THREAD

**Issue by tangbing0313** [Ormicron/chatViewTool#5]
您好，我在运行"java -jar chatViewTool.jar"时，提示“错误: 缺少 JavaFX 运行时组件, 需要使用该组件来运行此应用程序”，在win和mac系统里都有此提示，搜索后没有找到解决方案，请问如果解决，感谢

**Comment by Ormicron** [comment]
jdk11之后，javafx默认就被移除了，可以手动安装javafx或者使用11之前的jdk
